var tableData = [{
	accName: '耐毒珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '毒耐性'
}, {
	accName: '耐麻珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '麻痹耐性'
}, {
	accName: '耐眠珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '睡眠耐性'
}, {
	accName: '耐绝珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '昏厥耐性'
}, {
	accName: '耐爆珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '爆破异常状态的耐性'
}, {
	accName: '耐裂珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '裂伤耐性'
}, {
	accName: '耐防珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '防御力DOWN耐性'
}, {
	accName: '防音珠【3】',
	accRare: 'RARE6',
	accLevel: '■■■■■(5)',
	accDetail: '耳塞'
}, {
	accName: '防风珠【2】',
	accRare: 'RARE6',
	accLevel: '■■■■■(5)',
	accDetail: '风压耐性'
}, {
	accName: '耐震珠【2】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '耐震'
}, {
	accName: '攻击珠【1】',
	accRare: 'RARE7',
	accLevel: '■■■■■■■(7)',
	accDetail: '攻击'
}, {
	accName: '防御珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■■■■■(7)',
	accDetail: '防御'
}, {
	accName: '体力珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '体力增强'
}, {
	accName: '早复珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '回复速度'
}, {
	accName: '耐火珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '火耐性'
}, {
	accName: '耐水珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '水耐性'
}, {
	accName: '耐冰珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '冰耐性'
}, {
	accName: '耐雷珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '雷耐性'
}, {
	accName: '耐龙珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '龙耐性'
}, {
	accName: '耐属珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '属性异常状态的耐性'
}, {
	accName: '火炎珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■■■(5)',
	accDetail: '火属性攻击强化'
}, {
	accName: '流水珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■■■(5)',
	accDetail: '水属性攻击强化'
}, {
	accName: '冰结珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■■■(5)',
	accDetail: '冰属性攻击强化'
}, {
	accName: '雷光珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■■■(5)',
	accDetail: '雷属性攻击强化'
}, {
	accName: '破龙珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■■■(5)',
	accDetail: '龙属性攻击强化'
}, {
	accName: '毒珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '毒属性强化'
}, {
	accName: '麻痹珠【1】',
	accRare: 'RARE7',
	accLevel: '■■■(3)',
	accDetail: '麻痹属性强化'
}, {
	accName: '睡眠珠【1】',
	accRare: 'RARE7',
	accLevel: '■■■(3)',
	accDetail: '睡眠属性强化'
}, {
	accName: '爆破珠【1】',
	accRare: 'RARE7',
	accLevel: '■■■(3)',
	accDetail: '爆破属性强化'
}, {
	accName: '毒瓶珠【3】',
	accRare: 'RARE6',
	accLevel: '■(1)',
	accDetail: '毒瓶追加'
}, {
	accName: '痹瓶珠【3】',
	accRare: 'RARE7',
	accLevel: '■(1)',
	accDetail: '麻痹瓶追加'
}, {
	accName: '眠瓶珠【3】',
	accRare: 'RARE7',
	accLevel: '■(1)',
	accDetail: '睡眠瓶追加'
}, {
	accName: '爆瓶珠【3】',
	accRare: 'RARE7',
	accLevel: '■(1)',
	accDetail: '爆破瓶追加'
}, {
	accName: '解放珠【3】',
	accRare: 'RARE8',
	accLevel: '■■■(3)',
	accDetail: '属性解放/装填扩充'
}, {
	accName: '达人珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■■■■■(7)',
	accDetail: '看破'
}, {
	accName: '超心珠【2】',
	accRare: 'RARE8',
	accLevel: '■■■(3)',
	accDetail: '超会心'
}, {
	accName: '痛击珠【2】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '弱点特效'
}, {
	accName: '缩短珠【2】',
	accRare: 'RARE8',
	accLevel: '■■■(3)',
	accDetail: '集中'
}, {
	accName: '匠珠【3】',
	accRare: 'RARE8',
	accLevel: '■■■■■(5)',
	accDetail: '匠'
}, {
	accName: '拔刀珠【2】',
	accRare: 'RARE8',
	accLevel: '■■■(3)',
	accDetail: '拔刀术【技】'
}, {
	accName: '重击珠【2】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '破坏王'
}, {
	accName: 'KO珠【2】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: 'KO术'
}, {
	accName: '夺气珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '夺取耐力'
}, {
	accName: '飞燕珠【2】',
	accRare: 'RARE5',
	accLevel: '■(1)',
	accDetail: '飞燕'
}, {
	accName: '全开珠【2】',
	accRare: 'RARE7',
	accLevel: '■■■■■(5)',
	accDetail: '力量解放'
}, {
	accName: '挑战珠【2】',
	accRare: 'RARE7',
	accLevel: '■■■■■(5)',
	accDetail: '挑战者'
}, {
	accName: '无伤珠【2】',
	accRare: 'RARE7',
	accLevel: '■■■(3)',
	accDetail: '无伤'
}, {
	accName: '底力珠【2】',
	accRare: 'RARE7',
	accLevel: '■■■■■(5)',
	accDetail: '火场怪力'
}, {
	accName: '逆境珠【1】',
	accRare: 'RARE5',
	accLevel: '■(1)',
	accDetail: '不屈'
}, {
	accName: '逆上珠【2】',
	accRare: 'RARE7',
	accLevel: '■■■■■(5)',
	accDetail: '怨恨'
}, {
	accName: '鼓笛珠【1】',
	accRare: 'RARE6',
	accLevel: '■(1)',
	accDetail: '吹笛名人'
}, {
	accName: '增弹珠【2】',
	accRare: 'RARE7',
	accLevel: '■(1)',
	accDetail: '炮弹装填数UP'
}, {
	accName: '特射珠【1】',
	accRare: 'RARE7',
	accLevel: '■■(2)',
	accDetail: '特殊射击强化'
}, {
	accName: '炮术珠【1】',
	accRare: 'RARE8',
	accLevel: '■■■(3)',
	accDetail: '炮术'
}, {
	accName: '炮手珠【1】',
	accRare: 'RARE5',
	accLevel: '■■(2)',
	accDetail: '炮击手'
}, {
	accName: '强走珠【2】',
	accRare: 'RARE8',
	accLevel: '■■■(3)',
	accDetail: '跑者'
}, {
	accName: '体术珠【2】',
	accRare: 'RARE6',
	accLevel: '■■■■■(5)',
	accDetail: '体术'
}, {
	accName: '早气珠【2】',
	accRare: 'RARE7',
	accLevel: '■■■(3)',
	accDetail: '耐力急速回复'
}, {
	accName: '无食珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '饥饿耐性'
}, {
	accName: '回避珠【2】',
	accRare: 'RARE6',
	accLevel: '■■■■■(5)',
	accDetail: '回避性能'
}, {
	accName: '跳跃珠【2】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '回避距离UP'
}, {
	accName: '铁壁珠【1】',
	accRare: 'RARE7',
	accLevel: '■■■■■(5)',
	accDetail: '防御性能'
}, {
	accName: '速纳珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '收刀术'
}, {
	accName: '友爱珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■■■(5)',
	accDetail: '广域化'
}, {
	accName: '持续珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '道具使用强化'
}, {
	accName: '节食珠【1】',
	accRare: 'RARE5',
	accLevel: '■(1)',
	accDetail: '满足感'
}, {
	accName: '快吃珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '快吃'
}, {
	accName: '研磨珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '砥石使用高速化'
}, {
	accName: '爆师珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '炸弹客'
}, {
	accName: '茸好珠【1】',
	accRare: 'RARE8',
	accLevel: '■■■(3)',
	accDetail: '最爱菇类'
}, {
	accName: '加护珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '精灵加护'
}, {
	accName: '指示珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■■■(5)',
	accDetail: '指示随从'
}, {
	accName: '植学珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■■(4)',
	accDetail: '植生学'
}, {
	accName: '地学珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '地质学'
}, {
	accName: '浑身珠【2】',
	accRare: 'RARE7',
	accLevel: '■■■(3)',
	accDetail: '精神抖擞'
}, {
	accName: '投石珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '投射器装填数UP'
}, {
	accName: '潜伏珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '潜伏'
}, {
	accName: '耐冲珠【3】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '减轻胆怯'
}, {
	accName: '烟复珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '棉花孢子草的知识'
}, {
	accName: '沼渡珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '适应水场'
}, {
	accName: '标本珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '昆虫标本达人'
}, {
	accName: '耐瘴珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '瘴气耐性'
}, {
	accName: '嗅觉珠【1】',
	accRare: 'RARE5',
	accLevel: '■(1)',
	accDetail: '追踪达人'
}, {
	accName: '威吓珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '威吓'
}, {
	accName: '滑走珠【2】',
	accRare: 'RARE6',
	accLevel: '■(1)',
	accDetail: '滑走强化'
}, {
	accName: '治愈珠【1】',
	accRare: 'RARE6',
	accLevel: '■■■(3)',
	accDetail: '体力回复量UP'
}, {
	accName: '强弹珠【3】',
	accRare: 'RARE7',
	accLevel: '■(1)',
	accDetail: '通常弹·通常箭强化'
}, {
	accName: '贯通珠【3】',
	accRare: 'RARE8',
	accLevel: '■(1)',
	accDetail: '贯通弹·龙之箭强化'
}, {
	accName: '散弹珠【3】',
	accRare: 'RARE8',
	accLevel: '■(1)',
	accDetail: '散弹·刚射强化'
}, {
	accName: '昂扬珠【2】',
	accRare: 'RARE7',
	accLevel: '■■■(3)',
	accDetail: '强化持续'
}, {
	accName: '绝路珠【1】',
	accRare: 'RARE5',
	accLevel: '■(1)',
	accDetail: '死里逃生'
}, {
	accName: '龙封珠【3】',
	accRare: 'RARE7',
	accLevel: '■(1)',
	accDetail: '龙封力强化'
}, {
	accName: '整备珠【1】',
	accRare: 'RARE5',
	accLevel: '■■■(3)',
	accDetail: '整备'
}, {
	accName: '强弓珠【2】',
	accRare: 'RARE8',
	accLevel: '■(1)',
	accDetail: '解放弓的蓄力阶段'
}, {
	accName: '心眼珠【2】',
	accRare: 'RARE8',
	accLevel: '■(1)',
	accDetail: '心眼/弹道强化'
}, {
	accName: '强壁珠【2】',
	accRare: 'RARE7',
	accLevel: '■(1)',
	accDetail: '防御强化'
}, {
	accName: '刚刃珠【2】',
	accRare: 'RARE7',
	accLevel: '■(1)',
	accDetail: '刚刃研磨'
}, {
	accName: '无击珠【2】',
	accRare: 'RARE6',
	accLevel: '■(1)',
	accDetail: '无属性强化'
}];

var page = "1";
var size = '8';

$(function() {
	var searchHandler = function(p) {
		page = p || page;
		$("#listData").sugarTable({
			list: tableData,
			count: tableData.length,
			// noPaging: true,
			isLocal: true,
			pageDom: $("#page"),
			page: page,
			pageSize: size,
			fields: [{
				id: "accName",
				type: "text",
				name: "名称",
				width: "100",
			}, {
				id: "accRare",
				type: "text",
				name: "稀有度",
				width: "100",
				bold: true,
				colors: {
					"RARE5": "#8AECF8",
					"RARE6": "#7EA8FB",
					"RARE7": "#7555E1",
					"RARE8": "#FF985E",
				}
			}, {
				id: "accLevel",
				type: "text",
				name: "技能等级",
				width: "100",
			}, {
				id: "accDetail",
				type: "text",
				name: "技能说明",
			}],
			searchHandler: function(p) {
				searchHandler(p);
			}
		});
	}
	searchHandler("1");
});